[package]
org = "ballerina"
name = "file"
version = "1.3.0"
authors = ["Ballerina"]
keywords = ["file", "path", "directory", "filepath"]
repository = "https://github.com/ballerina-platform/module-ballerina-file"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.0.4"

[[platform.java11.dependency]]
path = "../native/build/libs/file-native-1.3.0.jar"

[[platform.java11.dependency]]
path = "./lib/org.wso2.transport.local-file-system-6.0.55.jar"


[[platform.java11.dependency]]
path = "../test-utils/build/libs/file-test-utils-1.3.0.jar"
scope = "testOnly"
